### PR TITLE
Introduce support for the convert verb

### PR DESCRIPTION
**Pull request by rickmark**
Signed-off-by: Rick Mark <rickmark@guardianapp.com>

### CODE REVIEW

**Comment by 0xbf00** [comment]
Thanks for contributing!

**Comment by rickmark** [comment]
No worries: i'm planning to add some native python XPlat support if you're open to that in this library

(basically if OS = Darwin use hdiutil, else maybe a mix of python and some C?)

**Comment by 0xbf00** [comment]
Sounds interesting, I just wonder how much complexity the changes would bring to this tiny library. I'm always open for PRs!

**Comment by rickmark** [comment]
It seems like we just have to create, and convert since Linux hfs can mount uncompressed images

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
